anguage: minimal

services: docker

before_install:
  - docker -v

install:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed navi83/udagram-api-feed:v1
  - docker tag udagram-api-user navi83/udagram-api-user:v1
  - docker tag udagram-frontend navi83/udagram-frontend:v1
  - docker tag reverseproxy navi83/reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push navi83/udagram-api-feed:v1
  - docker push navi83/udagram-api-user:v1
  - docker push navi83/udagram-frontend:v1
  - docker push navi83/reverseproxy:v1