apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    run: backend-feed
spec:
  ports:
  - port: 8080
    name: port1
    protocol: TCP
  - port: 8100
    name: port2
    protocol: TCP
  selector:
    run: backend-feed
