apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
  - port: 8100
    name: '8100'
    protocol: TCP
    targetPort: 80
  selector:
    run: frontend
    type: LoadBalancer