apiVersion: v1
kind: Service
metadata:
  name:  reverseproxy
  labels:
    run: reverseproxy
spec:
  ports:
  - port: 8080
    name:  port1
    protocol: TCP
  - port: 8100
    name:  port2
    protocol: TCP
  selector:
    run: reverseproxy